sequenceDiagram
    autonumber

    actor Client
    participant JobController
    participant JobService
    participant CylinderService
    participant ReportService
    participant JobRepository
    participant CylinderRepository
    participant ReportRepository

%% ========================
%% 1) Happy flow
%% ========================
    Client->>JobController: DELETE /jobs/{id} (token)
    activate JobController


    JobController->>JobService: deleteJob(id)
    activate JobService

    JobService->>JobRepository: findById(id)
    activate JobRepository
    JobRepository-->>JobService: JobEntity
    deactivate JobRepository

    Note right of JobService: Verwijderen in één transactie

    JobService->>CylinderService: getCylindersByJobId(id)
    activate CylinderService
    CylinderService->>CylinderRepository: findAllByJobId(id)
    activate CylinderRepository
    CylinderRepository-->>CylinderService: cylinders[]
    deactivate CylinderRepository
    CylinderService-->>JobService: cylinders[]
    deactivate CylinderService

    loop For each cylinder
        JobService->>ReportService: deletereportsByCylinderId(cylinderId)
        activate ReportService

        ReportService->>ReportRepository: findAllByCylinderId(cylinderId)
        activate ReportRepository
        ReportRepository-->>ReportService: reports[]
        deactivate ReportRepository

        loop For each plate
            ReportService->>ReportRepository: deleteById(plateId)
            ReportRepository-->>ReportService: deleted
        end

        deactivate ReportService

        JobService->>CylinderService: deleteCylinder(cylinderId)
        activate CylinderService
        CylinderService->>CylinderRepository: deleteById(cylinderId)
        activate CylinderRepository
        CylinderRepository-->>CylinderService: deleted
        deactivate CylinderRepository
        deactivate CylinderService
    end

    JobService->>JobRepository: deleteById(id)
    activate JobRepository
    JobRepository-->>JobService: deleted
    deactivate JobRepository

    JobService-->>JobController: success
    deactivate JobService

    JobController-->>Client: 204 No Content
    deactivate JobController


%% ========================
%% 2) Alternative flow: Job not found
%% ========================
    alt Job not found
        Client->>JobController: DELETE /jobs/{id} (token)
        activate JobController

        JobController->>JobService: deleteJob(id)
        activate JobService

        JobService->>JobRepository: findById(id)
        activate JobRepository
        JobRepository-->>JobService: empty
        deactivate JobRepository

        JobService-->>JobController: NotFoundException
        deactivate JobService

        JobController-->>Client: 404 Not Found
        deactivate JobController
    end
